### ISSUE TITLE
utils.py line 127: 'bool' object has no attribute 'nonzero'

### ISSUE THREAD

**Issue by BigBang019** [RorschachChen/DeepSigns-torch#1]
Hi, I have tried runing ```python run_whitebox.py```, but I got this:

![image](https://user-images.githubusercontent.com/46477713/166117910-cb9d8de6-0acb-40e3-8ca1-d8ecb1f364d1.png)

in line 127

```dataset.targets == target_class``` returns False, which does not have member function nonzero().

I have environment with

```
Python 3.9.0
torchvision 0.12.0
pytorch 1.11.0
pandas 1.4.2
scipy 1.8.0
```

**Comment by RorschachChen** [comment]
run_whitebox.py is CIFAR10 result while I haven't finished yet. but run_whitebox_ori.py is for MNIST which is fully finished. You can  try to modify from run_whitebox_ori.py to continue the result on CIFAR10.

**Comment by RorschachChen** [comment]
As for your question, the dataset.targets should be a tensor with length of the dataset, what this line is doing is to pick out the indices of the targets which are from the target class. Must be somewhere dataset.targets is not returned correctly.
